name: FTP Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run buildrtl

      - name: FTP Deploy
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          forceSsl: true # Set to true if you want to force SSL encryption
          localDir: "build" # Optional: specify the local directory to upload, default is the root of the repository
          remoteDir: "/public_html" # Specify the remote directory where files should be uploaded

          # You can also add other optional parameters as needed according to the documentation of the FTP action.
